### ISSUE TITLE
tutorials file doesn't work!

### ISSUE THREAD

**Issue by Kyle6699** [DTUWindEnergy/PyWake#1]
Pywake is really open source package? why I can't run "windturbines.ipynb" file in "\pywake\PyWake\tutorials" folder, seems like  Pywake is missing some files...
![image](https://user-images.githubusercontent.com/53243439/98902589-fa98c900-24f0-11eb-94a0-f0009510d36e.png)

Hope you can add my wechat to discuss about wind energy, my wechat id is 18374809474.

**Comment by madsmpedersen** [comment]
This Github repository is a mirror of the official https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake repository and is only existing to enable execution of notebooks in google colab.

So, please use the issue tracker in https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake

The PyWake\tutorials exists only because I have forgotten to delete it. It has been replaced by https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake/-/tree/master/docs/notebooks

You can see the notebooks in the documentation: https://topfarm.pages.windenergy.dtu.dk/PyWake/notebooks/WindTurbines.html

In the header there is a "Open in Colab" badge which allows you to open and run the notebook in google colab.

Kind regards
Mads
